name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Show Java & list files
        run: |
          java -version
          javac -version
          ls -R
      - name: Compile
        run: |
          mkdir -p out
          find . -name "*.java" -print0 | xargs -0 javac -d out
      - name: Smoke test (quit immediately)
        run: |
          printf "q\n" | java -cp out Main
