name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Compile
        run: |
          set -e
          mkdir -p out
          find src -type f -name '*.java' -print0 | xargs -0 javac -d out
      - name: Smoke test
        run: |
          printf "q\n" | java -cp out Main
